# Generated by Django 5.2.10 on 2026-04-16 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('color', models.CharField(default='#4F8EF7', max_length=7, verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('color', models.CharField(choices=[('#F75E5E', 'Червоний'), ('#4F8EF7', 'Синій'), ('#34C971', 'Зелений'), ('#9B6BF2', 'Фіолетовий'), ('#F7A134', 'Помаранчевий'), ('#F76EBF', 'Рожевий')], default='#4F8EF7', max_length=7, verbose_name='Колір')),
                ('icon', models.CharField(default='.', max_length=10, verbose_name='Іконка')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архівований')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('status', models.CharField(choices=[('todo', 'До виконання'), ('in_progress', 'В процесі'), ('in_review', 'На перевірці'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='todo', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('urgent', 'Терміново'), ('high', 'Високий'), ('normal', 'Нормальний'), ('low', 'Низький'), ('no_priority', 'Без пріоритету')], default='no_priority', max_length=20, verbose_name='Пріоритет')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Термін виконання')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата початку')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Виконано о')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Оціночний час (год)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиція')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архівовано')),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Виконавці')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasktrecker.task', verbose_name='Батьківське завдання')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='tasktrecker.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст коментаря')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Відредаговано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasktrecker.comment', verbose_name='Відповідь на')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasktrecker.task', verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Створено'), ('status_changed', 'Змінено статус'), ('priority_changed', 'Змінено пріоритет'), ('assignee_added', 'Додано виконавця'), ('assignee_removed', 'Видалено виконавця'), ('due_date_changed', 'Змінено термін'), ('commented', 'Коментар'), ('completed', 'Виконано'), ('archived', 'Архівовано')], max_length=30, verbose_name='Тип активності')),
                ('old_value', models.CharField(blank=True, max_length=255, verbose_name='Попереднє значення')),
                ('new_value', models.CharField(blank=True, max_length=255, verbose_name='Нове значення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasktrecker.task', verbose_name='Завдання')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Активність завдання',
                'verbose_name_plural': 'Активності завдань',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиція')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to='tasktrecker.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Список завдань',
                'verbose_name_plural': 'Списки завдань',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasktrecker.tasklist', verbose_name='Список'),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Робочий простір',
                'verbose_name_plural': 'Робочі простори',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tasktrecker.workspace', verbose_name='Робочий простір'),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tasktrecker.workspace', verbose_name='Робочий простір'),
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Власник'), ('admin', 'Адміністратор'), ('member', 'Учасник'), ('guest', 'Гість')], default='member', max_length=20, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktrecker.workspace')),
            ],
            options={
                'verbose_name': 'Учасник простору',
                'verbose_name_plural': 'Учасники простору',
                'unique_together': {('workspace', 'user')},
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspaces', through='tasktrecker.WorkspaceMember', to=settings.AUTH_USER_MODEL, verbose_name='Учасники'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('workspace', 'name')},
        ),
    ]
