# Generated by Django 5.2.10 on 2026-05-14 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrecker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('added_to_workspace', 'Вас додано до простору'), ('member_added', 'Новий учасник у просторі'), ('task_status_changed', 'Змінено статус завдання'), ('task_commented', 'Новий коментар до завдання'), ('comment_replied', 'Відповідь на ваш коментар'), ('task_edited', 'Завдання відредаговано'), ('task_deleted', 'Завдання видалено'), ('project_edited', 'Проект відредаговано'), ('project_deleted', 'Проект видалено'), ('comment_edited', 'Коментар відредаговано'), ('comment_deleted', 'Коментар видалено')], max_length=40, verbose_name='Тип')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Ініціатор')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач')),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'ordering': ['-created_at'],
            },
        ),
    ]
