# Generated by Django 5.2.10 on 2026-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrecker', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/images/', verbose_name='Прикріплене зображення'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст коментаря'),
        ),
    ]
